# Generated by Django 2.2.4 on 2019-08-26 13:48

from django.db import migrations, models
import django.db.models.deletion
import tools.image_funcs
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0002_auto_20190826_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to=tools.image_funcs.get_posters_path)),
                ('organizer_id', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('age_rate', models.PositiveSmallIntegerField()),
                ('is_approved', models.BooleanField()),
                ('max_members', models.PositiveIntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('status', models.CharField(choices=[('SOON', 'soon'), ('SUCCEED', 'succeed'), ('REJECTED', 'rejected')], default='SOON', max_length=16)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
                ('organizer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
