# Generated by Django 2.2.4 on 2019-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='event',
            name='age_rate',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
