# Generated by Django 2.2.4 on 2019-09-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190826_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
