# Generated by Django 2.2.4 on 2019-09-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
