# Generated by Django 2.2.4 on 2019-09-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('topic_id', models.UUIDField(editable=False)),
                ('parent_id', models.UUIDField(editable=False)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('DELETED', 'deleted'), ('OK', 'ok'), ('SUSPICIOUS', 'suspicious')], default='OK', max_length=16)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_type', to='contenttypes.ContentType')),
                ('topic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
