# Generated by Django 2.2.4 on 2019-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20190927_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='created_by',
        ),
    ]
