# Generated by Django 2.2.4 on 2019-09-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('UNPAID', 'Unpaid'), ('UNTRACKED', 'Untracked')], default='UNTRACKED', max_length=9)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='events.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'event_id')},
            },
        ),
    ]
