# Generated by Django 2.2.4 on 2019-09-20 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_top'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'event')},
        ),
    ]
