# Generated by Django 2.2.4 on 2019-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20190923_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('UNPAID', 'Unpaid'), ('UNTRACKED', 'Untracked'), ('CANCELLED', 'Cancelled')], default='UNTRACKED', max_length=9),
        ),
    ]
