# Generated by Django 2.2.4 on 2019-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20190906_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('TEMPORARILY_CLOSED', 'Temporarily closed'), ('WORKING', 'Working'), ('CLOSED', 'Closed')], default='WORKING', max_length=18),
        ),
    ]
