# Generated by Django 2.2.4 on 2019-09-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190909_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberslist',
            options={'ordering': ['organization__name']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
    ]
